# Funding options for CarHub

github: [Mostafa-SAID7]
# patreon: username
# open_collective: username
# ko_fi: username
# tidelift: npm/carhub
# community_bridge: project-name
# custom: ["https://buymeacoffee.com/username"]
